### PR TITLE
Bug: multiple CDATA comments don't get parsed as expected

### LINKED ISSUE #1: Bug: multiple CDATA comments don't get parsed as expected
First off - big thanks for this library. It's simple to use and on the whole it's been working great for me 👌

I have a valid XML file that is throwing an `Error: Failed to parse XML, expected token: ...` when using `parse()`. I've narrowed it down as much as I can to this reproducible issue that occurs when the document has multiple CDATA's:

```typescript
import { parse } from "https://deno.land/x/xml/mod.ts";
import { assertEquals } from "https://deno.land/std@0.95.0/testing/asserts.ts";

Deno.test("parse: xml syntax with multiple CDATA's", () =>
  assertEquals(parse(`
    <root>
      <text><![CDATA[ ]]></text>
      <text><![CDATA[ ]]></text>
    </root>`),
    {
      root: {
        text: [
          null,
          null
        ]
      },
    },
  ));
```

...fails with the following AssertionError diff:

```diff
    {
      root: {
+       text: [
+         null,
+         null,
+       ],
-       text: "]]></text>\n      <text><![CDATA[",
      },
    }
```

This looks to me like the parser is treating everything from the opening `<![CDATA[` through to the _final_ `]]` as a comment, rather than closing the first comment with the initial `]]`.

### PR DESCRIPTION
**Pull request by atenni**
Closes #1

### CODE REVIEW

**Comment by lowlighter** [comment]
Thanks a lot for this fix!
LGTM, can you run `deno fmt` to make the ci pass?

**Comment by atenni** [comment]
No worries - done.

**Comment by lowlighter** [comment]
Seems that raw.githubusercontent.com is currently down so the action to setup deno is broken, I'll retry later 👍

**Comment by lowlighter** [comment]
Thanks a lot 👍 !

**Pull request merged**
